os: Visual Studio 2015

before_build:
- dotnet restore src\vaerenberg.com\project.json
- dotnet restore test\vaerenberg.tests\project.json

build:
  project: Vaerenberg.sln
  parallel: true
  verbosity: minimal

test: off